# docker-compose.yml
# This file defines the services for your application stack.
# The 'frontend' service no longer uses runtime volumes to prevent mounting errors.

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: financial_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    networks:
      - financial-net

  frontend:
    build:
      context: ./frontend
    container_name: financial_frontend
    restart: always
    # REMOVED: The volumes section has been removed entirely from this service.
    # All frontend files are now part of the image built by frontend/Dockerfile.
    depends_on:
      - backend
    networks:
      - financial-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: financial_cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      # Set your TUNNEL_TOKEN in Portainer's stack environment variables
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} 
    depends_on:
      - frontend
    networks:
      - financial-net

networks:
  financial-net:
    driver: bridge
