# docker-compose.yml
# This file defines the services for your application stack.
# Added a healthcheck to prevent startup race conditions.

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: financial_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - financial-net

  frontend:
    build:
      context: ./frontend
    container_name: financial_frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy # MODIFIED: This makes the frontend wait.
    networks:
      - financial-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: financial_cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      # Set your TUNNEL_TOKEN in Portainer's stack environment variables
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} 
    depends_on:
      - frontend
    networks:
      - financial-net

networks:
  financial-net:
    driver: bridge
