# docker-compose.yml
# This file defines the services for your application stack.
# The 'frontend' service is now built from a Dockerfile for better stability.

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: financial_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    networks:
      - financial-net

  frontend:
    build:
      context: ./frontend  # MODIFIED: Build the frontend image from its directory
    container_name: financial_frontend
    restart: always
    volumes:
      # This volume now only mounts the index.html file, allowing you to edit it
      # without rebuilding the image. The configuration is baked into the image.
      - ./frontend/index.html:/usr/share/nginx/html/index.html # MODIFIED
    depends_on:
      - backend
    networks:
      - financial-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: financial_cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      # Set your TUNNEL_TOKEN in Portainer's stack environment variables
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} 
    depends_on:
      - frontend
    networks:
      - financial-net

networks:
  financial-net:
    driver: bridge
